//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:04:40 PM MSK 
//

package by.training.zakharchenya.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BankDeposit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankDeposit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/banks}Money">
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="demand"/>
 *             &lt;enumeration value="fixed"/>
 *             &lt;enumeration value="settlement"/>
 *             &lt;enumeration value="accumulation"/>
 *             &lt;enumeration value="saving"/>
 *             &lt;enumeration value="metal"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="responsiblemanager" type="{http://www.w3.org/2001/XMLSchema}string" default="Oleg I." />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankDeposit")
public class BankDeposit
    extends Money
{

    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "responsiblemanager")
    protected String responsiblemanager;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the responsiblemanager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsiblemanager() {
        if (responsiblemanager == null) {
            return "Oleg I.";
        } else {
            return responsiblemanager;
        }
    }

    /**
     * Sets the value of the responsiblemanager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsiblemanager(String value) {
        this.responsiblemanager = value;
    }

}
