//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:04:40 PM MSK 
//

package by.training.zakharchenya.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.banks package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bankdeposit_QNAME = new QName("http://www.example.com/banks", "bankdeposit");
    private final static QName _Cardaccount_QNAME = new QName("http://www.example.com/banks", "cardaccount");
    private final static QName _Money_QNAME = new QName("http://www.example.com/banks", "money");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.banks
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link Banks }
     * 
     */
    public Banks createBanks() {
        return new Banks();
    }

    /**
     * Create an instance of {@link CardAccount }
     * 
     */
    public CardAccount createCardAccount() {
        return new CardAccount();
    }

    /**
     * Create an instance of {@link BankDeposit }
     * 
     */
    public BankDeposit createBankDeposit() {
        return new BankDeposit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankDeposit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/banks", name = "bankdeposit", substitutionHeadNamespace = "http://www.example.com/banks", substitutionHeadName = "money")
    public JAXBElement<BankDeposit> createBankdeposit(BankDeposit value) {
        return new JAXBElement<BankDeposit>(_Bankdeposit_QNAME, BankDeposit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/banks", name = "cardaccount", substitutionHeadNamespace = "http://www.example.com/banks", substitutionHeadName = "money")
    public JAXBElement<CardAccount> createCardaccount(CardAccount value) {
        return new JAXBElement<CardAccount>(_Cardaccount_QNAME, CardAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Money }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/banks", name = "money")
    public JAXBElement<Money> createMoney(Money value) {
        return new JAXBElement<Money>(_Money_QNAME, Money.class, null, value);
    }

}
